name: lazy_ants
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  flutter_bloc: ^8.1.6
  auto_route: ^9.2.2
  drift: ^2.20.0
  dio: ^5.7.0
  drift_flutter: ^0.2.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  injectable: ^2.4.4
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  drift_dev: ^2.20.1
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
